--- 
abstract: A Data::Package class for CSV data using Parse::CSV
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  ExtUtils::MakeMaker: 6.11
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Data-Package-CSV
no_index: 
  directory: 
    - inc
    - t
requires: 
  Data::Package::File: 1.02
  File::ShareDir: 0.05
  File::Spec: 0.80
  Parse::CSV: 1.00
  perl: 5.005
version: 1.00
